apiVersion: v1
kind: Pod
metadata:
  name: kevin-testing-loop-messages
spec:
  containers:
    - name: kevin-test-loop-python
      image: ghcr.io/kevinpinscoe/python-docker-fun:latest
      imagePullPolicy: Always
