# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Docker build artifact for python-docker-fun

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - name: login to GitHub Container Registry
       uses: docker/login-action@v1
       with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
     - uses: actions/checkout@v3
     - name: Build the Docker image
       run: docker build . --file Dockerfile --tag kevin_test_loop_python:1.0
     - name: Tag the Docker image
       run: docker tag kevin_test_loop_python:1.0 ghcr.io/kevininscoe/kevin_test_loop_python:1.0
     - name: Push the Docker image to the registry
       run: docker push ghcr.io/kevininscoe/kevin_test_loop_python:1.0
