# This workflow will install Python dependencies and build a container
# to be published on my public packages deployable as a k8s pod

name: Docker build container for python-docker-fun

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
     - name: login to GitHub Container Registry
       uses: docker/login-action@v1
       with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
     - name: Set up Python 3.11
       uses: actions/setup-python@v4
       with:
        python-version: "3.11"
     - uses: actions/checkout@v3
     - name: Build the Docker image
       run: docker build . --file Dockerfile --tag kevin_test_loop_python:1.0
     - name: Tag the Docker image
       run: docker tag kevin_test_loop_python:1.0 ghcr.io/${{ github.actor }}/kevin_test_loop_python:1.0
     - name: Push the Docker image to the registry
       run: docker push ghcr.io/${{ github.actor }}/kevin_test_loop_python:1.0
     - name: Make note of succcess
       run: SUCCESS="yes"
           echo "SUCCESS=${SUCCESS}" >> $GITHUB_OUTPUT
